### ISSUE TITLE
Compiler#withClasspathFrom not usable on Windows

### ISSUE THREAD

**Issue by f4lco** [google/compile-testing#156]
`Compiler#withClasspathFrom` (because of `Compiler#getClasspathFromClassloader`) appears to get a couple of things wrong on the Windows operating system. The collected classpaths look something like this:

> /C:/Program%20Files/JetBrains/IntelliJ%20IDEA%202018.2.4/lib/idea_rt.jar

(This is simply the first entry - the actual jarfile is not relevant, and other paths are mangled the same way).

I'm not an expert on the matter, but the following things make me nervous (and let my compilation fail due to classes the compiler fails to resolve):
* leading slash
* slashes instead of backslash
* URL encoding in paths
* In addition, different paths are concatenated using ":" (colon), which should be ";" (semicolon) for Windows operating systems.

To prove my theory, I altered the contents of `classpaths` using a debugger by evaluating the following statements at `Compiler.java:197`:

```java
Set<String> newClasspaths = new LinkedHashSet<>();
for (String cp : classpaths) {
  newClasspaths.add(URLDecoder.decode(cp.substring(1), "utf-8").replace('/', '\\'));
}
String newCp = Joiner.on(";").join(newClasspaths);
classpaths.clear();
classpaths.add(newCp);
```
Then I could compile my sources without error, which is the expected result in this case. Also the same project / testcase is fine when executed under, e.g., Mac OS.

Possible workaround: instead of using

    Compiler.javac().withProcessors(new MyProcessor())
      .withClasspathFrom(getClass().getClassLoader());

I turned to

    Compiler.javac().withProcessors(new MyProcessor())
      .withOptions("-classpath", System.getProperty("java.class.path"));

which might represent a portable way of stating "I would like my sources-to-compile to have access to the current classpath" (I'm very unsure about this).
I expect `Compiler#withClasspathFrom` to collect a functioning classpath on the Windows operating system. I did not check but can imagine that the URL encoding can also affect classpath validity on other platforms.

**Comment by f4lco** [comment]
Yes I'm indeed referring to v0.15. Yes, above proposal seems like a probable fix.

I just had a look at the current master. May I ask why `Compiler#withClasspathFrom(ClassLoader)` has been deprecated? Because this indicates the method might go away soonish, it does not appear to be a sustainable fix.
I use above construct to put the annotation-to-process on the compiler's classpath in order to test the accompanying annotation processor. To my knowledge, this is not easily doable with the suggested alternative `Compiler#withClasspath(Iterable<File>)`.
Are there other recommended ways of doing that?

**Comment by tbroyer** [comment]
By default, the compilation will use the system classpath, so you shouldn't need either `withClasspathFrom(getClass().getClassLoader())` or `withOptions("-classpath", System.getProperty("java.class.path"))`, and the compiler should see your annotations.

For instance, https://github.com/google/auto/blob/02fb8f93d2ac08e2fdfbba27731b185cb73fa0f9/value/src/test/java/com/google/auto/value/processor/AutoValueCompilationTest.java uses the `AutoValue` annotation without the need to explicitly set the classpath for the compilation.

**Comment by f4lco** [comment]
My bad 🙈. Yes you are right I can get away without altering the classpath at all. There must have been another error in my setup which appeared to be a classpath issue in the first place and which is now resolved.

OK what we are left with? A now deprecated method which fails under some circumstances, which is going to be removed anyway, I suppose.
Thank you very much for listening, and for being such responsive 👍
