### ISSUE TITLE
Release a new version?

### ISSUE THREAD

**Issue by ZacSweers** [google/compile-testing#163]
This library uses now-deleted APIs in Google Truth, but hasn't been released since 2017

**Comment by ronshapiro** [comment]
I sent a change to update some other dependency versions. I'll sync that out and then make a release.

**Comment by ZacSweers** [comment]
Thanks!

**Comment by ethlo** [comment]
Anything happening here?

**Comment by cpovirk** [comment]
https://github.com/google/compile-testing/releases/tag/release_0_16, on its way to Maven Central in the next hour or so. Sorry for taking so long on this.

**Comment by ZacSweers** [comment]
Thanks!

**Comment by cpovirk** [comment]
https://repo1.maven.org/maven2/com/google/testing/compile/compile-testing/0.16/
