### ISSUE TITLE
Alternate propositions for generated source

### ISSUE THREAD

**Issue by cgruber** [google/compile-testing#17]
I'm thinking of something on the order of

```
ASSERT.about(javaSources()).that(source)
    .compileswithoutError().and()
    .generatesSourceAtPath("path").containingSnippets("some valid snippet").and()
    .generatesSourceAtPath("path").containingMethods(
        "method signature1", 
        "method signature2").and()
    .generatesSourceAtPath("path").containingFields(
        "String foo", 
        "private Blah blah").and()
     ...
```

Doesn't have to be exactly like this, and the snippets version could stand in for all the rest.  But it would be nice to ask things about the generated output while testing.

**Comment by ronshapiro** [comment]
I'm going to declare bug bankruptcy here. This may be useful, but it's stale. Let's reopen a new bug if there's a feature that we think is still missing.
