### ISSUE TITLE
The resource was closed incorrectly

### ISSUE THREAD

**Issue by QiAnXinCodeSafe** [google/compile-testing#170]
The code may throw an exception before the resource is closed，you should use try-catch-finally or try-with-resource to close resource，
https://github.com/google/compile-testing/blob/ac382a970e3b574454bd8760b5e184afdee5f172/src/test/java/com/google/testing/compile/JarFileResourcesCompilationTest.java#L52-L56

**Comment by nglorioso** [comment]
Thanks for the comment. Since this runs as part of the initializer of a test method, and the TemporaryFolder will clean out the directory if the before method fails, I don't think this is worth changing.
