### ISSUE TITLE
Seeking an equivalent to GeneratingProcessor

### ISSUE THREAD

**Issue by robinroos** [google/compile-testing#183]
com.google.testing.compile.CompilationTest uses GeneratingProcessor to write source to a file, but that class is only present in src/test/java and is not part of the compile-testing:0.18 artifact.

What publicly-available Processor might I use to have generated source written to disk, where I can view it, and from which I can make assertions?

I note that package-info suggests testing in this way, e.g. 
`.generatedSourceFile("GeneratedHelloWorld")`
but I am unable to get such a test to run.

My test, taken largely from package-info. is:

```
    @Test
    public void compilationOfJavaResourceWithNoAnnotationsGeneratedExpectedTarget() {
        Compilation compilation =
                javac().compile(JavaFileObjects.forResource("HelloWorld.java"));
        assertThat(compilation).succeeded();
        assertThat(compilation)
                .generatedSourceFile("GeneratedHelloWorld")
                .hasSourceEquivalentTo(JavaFileObjects.forResource("GeneratedHelloWorld.java"));
    }
```

For which I get:

```
expected to generate file: /HelloWorld.java
in location              : SOURCE_OUTPUT
it generated:

	at com.hubio.ice.customerportal.widgets.generator.json.GenerateJsonSerializerProcessorTest.compilationOfJavaResourceWithNoAnnotationsGeneratedExpectedTarget(GenerateJsonSerializerProcessorTest.java:34)
	
```

**Comment by robinroos** [comment]
Attaching the test case.  Note that I am not applying any Processors.

[GenerateJsonSerializerProcessorTest.txt](https://github.com/google/compile-testing/files/4105354/GenerateJsonSerializerProcessorTest.txt)

**Comment by netdpb** [comment]
Annotation processing is a framework that lets you create your own [annotation processor](https://docs.oracle.com/javase/8/docs/api/javax/annotation/processing/Processor.html) to generate whatever source you need to. The `GeneratingProcessor` you see there is just there to test that Compile-Testing is able to make assertions on arbitrary generated source.

Closing this issue. If you have further questions about Java annotation processing, I think stackoverflow will be helpful.
