### ISSUE TITLE
Annotation processor's Filer can't read the files being compiled

### ISSUE THREAD

**Issue by jbreathe** [google/compile-testing#189]
I have a code in my annotation processor and it works fine when I compile sources using this annotation processor (with Maven, for example).
Simplified version of code looks like this:
```java
try {
    FileObject fileObject = filer.getResource(StandardLocation.SOURCE_PATH, "org.example", "MyMapper.java");
    String content = fileObject.getCharContent(false).toString();
} catch (IOException e) {
    // ...
}
```
When I try to test my code using compile-testing, it fails on the first line with error:
```
java.io.FileNotFoundException: org.example/MyMapper.java
```
If I change the location from ```StandardLocation.SOURCE_PATH``` to ```StandardLocation.SOURCE_OUTPUT```), then Filer will successfully return FileObject in the first line, but then the code will fail in the second line, where I try to read the contents of FileObject:
```
java.io.FileNotFoundException
```
FileNotFound without any message.

I have a small repro in this branch - https://github.com/jbreathe/corgi/tree/ct-issue.
You can find test itself [here](https://github.com/jbreathe/corgi/blob/ct-issue/corgi-mapper/src/test/java/io/github/jbreathe/corgi/mapper/CorgiProcessorTest.java).
And class where Filer used [here](https://github.com/jbreathe/corgi/blob/ct-issue/corgi-mapper/src/main/java/io/github/jbreathe/corgi/mapper/source/SourceFilesSpoonParser.java) (getFileObject and readAllLines methods).

Version of Java is 14.

Maybe the second one is a known issue?
And about the first one - can I read FileObject using ```StandardLocation.SOURCE_PATH```?

UPD: to be more clear - I'm trying to read a file that is passed to "Compiler#compile". See test for more details.

**Comment by cpovirk** [comment]
I have nothing actionable for you, but: This does not surprise me :(

[Although javac has an API written in terms of `Path`, it converts to `File` objects internally.](https://github.com/google/error-prone/blob/b443cc8ec4ef04f1d927f534bca6fb907a052668/test_helpers/src/main/java/com/google/errorprone/ErrorProneInMemoryFileManager.java#L103-L114) This means that in-memory filesystem implementations (like [the one used by Compile-Testing](https://github.com/google/compile-testing/blob/master/src/main/java/com/google/testing/compile/InMemoryJavaFileManager.java)) don't always work as expected.

It's possible that the right solution is for Compile-Testing to stop using an in-memory filesystem. (I don't know specifically what the in-memory filesystem buys us offhand.) Unless we do that, I'm not sure if there's a workaround.

But I haven't looked into any of this in detail for Compile-Testing.

**Comment by jbreathe** [comment]
Thank you, @cpovirk!
I thought about something similar today.
I think JavaFileObjects.forResource instead of "forSourceString" can do the trick.
Will try it tomorrow!
Thank you once again!

**Comment by jbreathe** [comment]
Six months later, I figured out that the problem was in Maven. Seems that Maven is implicitly adding "-sourcepath" and that's why everything works.
I tried to compile simple example with plain javac:
`javac -cp ./proc_path -processor myproc.CopyingProcessor -d ./bin src/test/Main.java`
and it doesn't work, when
`javac -cp ./proc_path **-sourcepath ./src** -processor myproc.CopyingProcessor -d ./bin src/test/Main.java`
does.
When we compile inside another Java program, for example with Compile-Testing, we don't have any project layout and the equivalent wihout "src" would be:
`javac -sourcepath . test/Main.java`
Seems that my problem can be solved by passing the current directory (File(".")) to the sourcepath, except that we are dealing with in-memory JavaFileObjects.
However, adding the sourcepath to the Compiler is a good idea. This way it will be possible to work around my problem by working with regular JavaFileObjects (from #forResource, for example) and their sourcepath passed with `withSourcepath(Iterable<File> sourcePath)`.
The original problem with in-memory JavaFileObjects is also easy to fix just by adding in-memory JavaFileObjects to the cache and handling them in [InMemoryJavaFileManager](https://github.com/google/compile-testing/blob/master/src/main/java/com/google/testing/compile/InMemoryJavaFileManager.java)#getFileForInput before calling `super.getFileForInput`.

By the way, the tests still pass if you comment out `if (location.isOutputLocation())` branch in InMemoryJavaFileManager#getFileForInput. Probably, because com.sun.tools.javac.processing.JavacFiler call [JavaFileManager#getFileForInput](https://docs.oracle.com/javase/8/docs/api/javax/tools/JavaFileManager.html#getFileForInput-javax.tools.JavaFileManager.Location-java.lang.String-java.lang.String-) only for _not_ [JavaFileManager.Location#isOutputLocation](https://docs.oracle.com/javase/8/docs/api/javax/tools/JavaFileManager.Location.html#isOutputLocation--), so I don't know how this branch can be executed... Even so, it is better to leave it as it is, because I might be wrong.

About the original problem, my proposed solution is to add one more method to the Compiler, for example `withInMemorySourcePath()`, which will tell you to add in-memory JavaFileObjects to cache.
To make it work, an interface for in-memory JavaFileObject must be added to distinguish in-memory objects from regular ones.
Even with another solution with filesystem JavaFileManager, the method to add files made from Strings (#forSourceString) to the sourcepath is still required.
So, I think it is a naming thing - to name such method `withInMemorySourcePath()` or somehow... I don't know... To have some space in the future in case of JavaFileManager refactoring.

Here is the PR with the proposed changes (with new methods `withSourcepath(Iterable<File> sourcePath)` and `withInMemorySourcePath()`) and some tests - #209.

**Comment by netdpb** [comment]
Without adding a feature to Compile Testing, can you call `.withOptions("-sourcepath", "./src")` so that your test works?

**Comment by jbreathe** [comment]
Hi, @netdpb!
I tried.
It doesn't help because we are dealing with in-memory JavaFileObjects here.
CT's InMemoryJavaFileManager delegates most part of the work to the underlying JavacFileManager (in case of the Sun's compiler) that works with usual filesystem files. '-sourcepath' will help only for this type of FileObjects (filesystem).
So, the workaround is to handle in-memory JavaFileObjects in the InMemoryJavaFileManager or, as @cpovirk said, stop using an in-memory filesystem.

**Comment by netdpb** [comment]
I'm still not sure I understand. `InMemoryJavaFileManager` assumes only _output_ files are in the in-memory cache, and delegates to the standard file manager for input files. The standard file manager should honor the `-sourcepath` argument and look in the filesystem, for `StandardLocation.SOURCE_PATH`. The `MyMapper.java` file is on the filesystem, not in memory—right?

I'm a little surprised by the error message you got, since it refers to "org.example/MyMapper.java", which is not a correct relative file path.

**Comment by jbreathe** [comment]
>The MyMapper.java file is on the filesystem, not in memory—right?

It is in-memory JavaFileObject. The test itself looks something like this:
```java
@Test
void mapTwoStructsTest() {
    @Language("java")
    String code = """
            package org.example;
            import io.github.jbreathe.corgi.api.*;
            import java.math.BigDecimal;
            @Mapper
            interface MyMapper {
                @Mapping
                MyEntity map(MyDto dto);
                class MyEntity {
                    private String name;
                    private BigDecimal amount;
                    void setName(String name) {
                        this.name = name;
                    }
                    void setAmount(BigDecimal amount) {
                        this.amount = amount;
                    }
                }
                class MyDto {
                    private String name;
                    private BigDecimal amount;
                    String getName() {
                        return name;
                    }
                    BigDecimal getAmount() {
                        return amount;
                    }
                }
            }
            """;
    JavaFileObject input = JavaFileObjects.forSourceString("org.example.MyMapper", code);
    CorgiProcessor processor = new CorgiProcessor();
    Compiler compiler = Compiler.javac()
            .withOptions("--release", "9")
            .withOptions("-sourcepath", "./src")
            .withProcessors(processor);
    Compilation compilation = compiler.compile(input);
    assertEquals(0, compilation.errors().size());
}
```
>I'm a little surprised by the error message you got, since it refers to "org.example/MyMapper.java"

Me too. If I remember correctly, this is because getName() method is not overridden in the *com.google.testing.compile.InMemoryJavaFileManager.InMemoryJavaFileObject*, but this needs to be double checked.

**Comment by netdpb** [comment]
OK, I think I understand a bit more.

It looks like you are trying to read, as a resource, the source file that is currently being processed by the annotation processor. In the test, that's the `JavaFileObject` that's being passed to `compiler.compile(input)`. That is obviously a source file.

I think that's a fair requirement. I'll rename this issue to reflect the specific problem.

**Comment by jbreathe** [comment]
@netdpb, you got it right!
> I don't think we need a new API like withInMemorySourcePath() for this.

Yeah, it would be great to have this kind of functionality without any API changes. Thank you!
