### ISSUE TITLE
Android/AGP 3.6.2 breaks JavaFileObjects.forResource

### ISSUE THREAD

**Issue by glureau-betclic** [google/compile-testing#190]
SSCCE: https://github.com/glureau/AGP_3_6_JavaFileObjects_forResources

**Expected:** Same behaviour on Android Gradle Plugin (AGP) 3.5.0 and AGP 3.6.2, we should be able to retrieve the URL of the file.
**Actual:** On AGP 3.5.0, URL is retrieved, on AGP 3.6.2, an exception is thrown. The source code

    JavaFileObjects.forResource("FindMe.java")

results in 

    IllegalArgumentException: resource FindMe.java not found.

**Workaround:**

Instead of using the String path for resolution, it's possible to use the URL signature while resolving manually the directory (with obvious drawbacks):

    JavaFileObjects.forResource(File("build/intermediates/sourceFolderJavaResources/debug/FindMe.java").toURI().toURL())
-----------

For reference, the issue has been found here: https://github.com/airbnb/epoxy/pull/939

**Comment by tbroyer** [comment]
`forResource` uses `Class.getResource()` (https://github.com/google/compile-testing/blob/b4eaa92f272e799c61221eebd4fe30bc2532d230/src/main/java/com/google/testing/compile/JavaFileObjects.java#L155-L162, https://guava.dev/releases/snapshot-jre/api/docs/com/google/common/io/Resources.html#getResource-java.lang.String-, https://docs.oracle.com/javase/8/docs/api/java/lang/ClassLoader.html#getResource-java.lang.String-), so if it breaks, then it means AGP's behavior has changed. If that's not an expected change, then it's a bug in AGP, not in compile-testing.

**Comment by glureau-betclic** [comment]
Thanks for the quick response and for your time! You're right, Resources.getResource returns null with AGP 3.6.3, while returning a proper path in 3.5.0

Should I go deeper and track if guava has a "limitation" here? (not sure to understand all the implications there :/)

Do you know how to contact AGP developers? Looks like a google close-source project, I tried a tweet but not sure it'll have enough visibility, if ever you've some inputs :)

**Comment by tbroyer** [comment]
See https://developer.android.com/studio/report-bugs

**Comment by glureau-betclic** [comment]
For future devs having the same issue: https://issuetracker.google.com/issues/154441059
