### ISSUE TITLE
Fix incompatibility vs. Truth

### ISSUE THREAD

**Issue by frankbenoit** [google/compile-testing#195]
the libary truth has a breaking changein with 0.46, that the class Subject removed its generic args.
This is already solved in the sources of compile-testing, but not yet release.
Please do a release, and set the truth dependency to >= 0.46 (1.0.1).

see also: https://github.com/google/auto/issues/891

**Comment by cpovirk** [comment]
"Fixed" by https://github.com/google/compile-testing/commit/b867b4a5cf385a673fc05b63362b223941f47e3e, but we'll need to do a release, as you say.

**Comment by cpovirk** [comment]
https://github.com/google/compile-testing/releases/tag/compile-testing-0.19

https://repo1.maven.org/maven2/com/google/testing/compile/compile-testing/0.19/
