### ISSUE TITLE
If there are invalid class in the source file, the process method of processor will not be invoked.

### ISSUE THREAD

**Issue by vipcxj** [google/compile-testing#213]
for example:
```java
class A extend B<C> {
    D method() { return null; }
}
```
Here C and D is invaild at annotation processing phases because they are generated classes by some annotation processor. So they will be valid at compile phases. My processor need to analysis them through ast. But the process method is not invoked at all.(The init method is invoked.) On the other hand, If I type mvn test in the console, the process method is invoked.

This is my project struct
project
- src
  - main
    - java
      - my.package
        - MyProcessor.java
  - test
    - java
      - my.package
        - MyTest.java
    - resources
      - my.package
        - MyTestClassWithInvalidClass.java

And this is my test class
```java
public class Tester {

    @Test
    public void test() {
        JavaFileObject fileObject = JavaFileObjects.forResource("my.package.MyTestClassWithInvalidClass".replaceAll("\\.", "/") + ".java");
        Compilation compilation = Compiler.javac()
                .withProcessors(new TestProcessor())
                .compile(fileObject);
        CompilationSubject.assertThat(compilation).failed();
    }
}
```

**Comment by vipcxj** [comment]
The issue only happen when using ide debug. Invoke maven test in the command line all ok. I think some exception happened because of lack some environment when debug in ide, The processors only be inited, then crash, but the exceptions are all swallowed by compile-testing, it only complain the source file is invaild, because the processor not invoked.,

**Comment by netdpb** [comment]
It sounds like you have a problem with your IDE configuration. Perhaps it's not configured to know about your `src/test/resources` directory?

In any case, I'm closing this as it's not likely a bug in Compile Testing. You might get more responses from people in the community if you ask your question on stackoverflow.com. (I don't even know which IDE you're using.)
