### ISSUE TITLE
Compile with Lombok Annotations

### ISSUE THREAD

**Issue by Mom0aut** [google/compile-testing#329]
Hello,

i generate Java Files with Lombok Annotations from my own Annotation Processor, when testing i get the following compile error : "is not abstract and does not override abstract method".

Test Case

``` @Test
    void process() {
        ReleationProcessor releationProcessor = new ReleationProcessor();
        Compilation compilation = javac()
                .withProcessors(releationProcessor)
                .compile(JavaFileObjects.forResource("TestFile.java"));
        CompilationSubject.assertThat(compilation).succeeded();
```

Generated File from  Annotation Processor

```
@Setter
@Getter
public final class Testing implements Model {
  private String targetType;
}
```

On my normal build everything works fine.
Is there some way to ignore the compile error or add an option for Lombok Annotations.

Ty Mom0

**Comment by chaoren** [comment]
What's the command line for your normal build?

**Comment by Mom0aut** [comment]
The normal build is with maven or via the internal intellij build. Any tipps how i can compare those builds with the plugin Compiler?

**Comment by Mom0aut** [comment]
Ty for your answer, i tried to compare with the mvn -X flag and compiled with the exact same classpath but in the end the compiler cant compile with lombok annotations(getter/setter have no override annotation).

Do u have maybe any example with working compilation with lombok annotations ?

**Comment by Mom0aut** [comment]
I changed the Lombok Getter and Setter for my generated Classes to AutoValue and now i can compile within the IDE and with the Unit test.
Maybe someone could use this information...

**Comment by tbroyer** [comment]
Fwiw, you would have to add the Lombok _processor_ to the `withProcessors` so it can do its _(black) magic_.

**Comment by esfomeado** [comment]
@tbroyer  How?

**Comment by TheBlob42** [comment]
> @tbroyer How? What is the Lombok processor class name?

I came here with the same question, luckily some other developers on Github using `compile-testing` figured it out so I found a solution working for me. I don't take credit for it and there are other solutions for this (use Github's search and you'll probably find more), but this is the one I am using now:

```java
public class YourTestClass {

    Compiler compiler;

    @BeforeEach
    public void setupCompiler() throws Exception {
        Class<?> lombokAnnotationProcessor = getClass().getClassLoader().loadClass("lombok.launch.AnnotationProcessorHider$AnnotationProcessor");
        Class<?> lombokClaimingProcessor = getClass().getClassLoader().loadClass("lombok.launch.AnnotationProcessorHider$ClaimingProcessor");
        compiler = Compiler.javac()
            .withProcessors(
                    (Processor) lombokAnnotationProcessor.getDeclaredConstructor().newInstance(),
                    (Processor) lombokClaimingProcessor.getDeclaredConstructor().newInstance(),
                    your custom processors...
                    );
    }

    @Test
    public void yourTest() {
        ...
    }
}
```

The names of the annotation processors used by lombok can be found in the `META-INF/services/javax.annotation.processing.Processor` file when you extract the jar (or you need to check their build setup). But both of those classes are hidden, so you can not simply import them into your tests. Therefore the have to be loaded via the classloader.
