### ISSUE TITLE
compilesWithoutError failure is hard to understand without the generated sources.

### ISSUE THREAD

**Issue by lukesandberg** [google/compile-testing#34]
If I have a generated source with a compile error, it is difficult to understand what the error is from the error message alone since there is no easy way to compare to the actual source.

It would be nice if the error message dumped a copy of the source file annotated with the compile errors.  In general having easier access to the generated sources would make iterative test development easier.

**Comment by ronshapiro** [comment]
I believe this is stale. Closing for now, and we can reopen if it's not fully implemented.
