### ISSUE TITLE
Release 0.20?

### ISSUE THREAD

**Issue by rmannibucau** [google/compile-testing#341]
Hi all,

the enhancements on forSource (be able to read source content) are great but not yet released AFAIK, is it possible to get it on central please?

Thanks

**Comment by chaoren** [comment]
You mean [this commit](https://github.com/google/compile-testing/commit/95e749db88ef949fb29ca1348d96cf6583331885), right?  Correct, it's not in a release yet. @cpovirk any plans for when the next release might be?

**Comment by cpovirk** [comment]
There's no particular schedule, but I'd say there's enough reason to make one, so here you go:

- https://github.com/google/compile-testing/releases/tag/compile-testing-0.20
- https://repo1.maven.org/maven2/com/google/testing/compile/compile-testing/0.20/

(And https://github.com/google/compile-testing/pull/342 should make the next release easier, I hope.)
