### ISSUE TITLE
Output information about why an assertion failed

### ISSUE THREAD

**Issue by xenoterracide** [google/compile-testing#365]
```
ClassAnnotationTest > testImmutable() FAILED
    com.google.common.truth.AssertionErrorWithFacts at ClassAnnotationTest.java:68
```
All this tells me is *which* assertion failed, but not why. Having to println a bunch of data in each test, and guess what the framework is looking for is awful.

```java
    compilation.diagnostics().forEach(System.out::println);
    compilation
      .generatedSourceFiles()
      .forEach(f -> {
        System.out.println(f.getName());
        try (var s = f.openInputStream()) {
          s.transferTo(System.out);
        } catch (IOException e) {
          throw new RuntimeException(e);
        }
      });

    assertThat(compilation.generatedFiles()).hasSize(3);
    CompilationSubject.assertThat(compilation).succeededWithoutWarnings();
    CompilationSubject
      .assertThat(compilation)
      .generatedSourceFile("SOURCE_OUTPUT/HelloWorldBuilder.java")
      .hasSourceEquivalentTo(JavaFileObjects.forSourceString("HelloWorldBuilder", "class Test {}"));
```
currently not sure why this is failing. Also #45

**Comment by cpovirk** [comment]
All the failure paths that I traced for those methods appear to include a failure message, so something weird is going on. I understand that the entire problem here is that it's difficult to see which assertion is failing, but if you can hunt it down (even if by commenting out assertions, starting at the end), that could help us figure out what's going on. (Could it be an old version of Compile-Testing? Could it be the build system that is hiding the message and stack trace?)

**Comment by xenoterracide** [comment]
https://github.com/xenoterracide/bygger

**Comment by cpovirk** [comment]
```
diff --git a/build.gradle.kts b/build.gradle.kts
index 7b37840..277f6da 100644
--- a/build.gradle.kts
+++ b/build.gradle.kts
@@ -1,3 +1,6 @@
+import org.gradle.api.tasks.testing.logging.TestExceptionFormat
+import org.gradle.api.tasks.testing.logging.TestLogEvent
+
 group = "com.xenoterracide"
 version = "0.1.0-SNAPSHOT"
 
@@ -17,3 +20,11 @@ dependencies {
 tasks.dependencies {
   dependsOn(subprojects.map { it.tasks.dependencies })
 }
+
+tasks.withType<Test> {
+  testLogging {
+    events = setOf(TestLogEvent.FAILED)
+
+    exceptionFormat = TestExceptionFormat.FULL
+  }
+}
```

->

```
ClassAnnotationTest > testImmutable() FAILED
    Compilation produced the following diagnostics:
    /SOURCE_OUTPUT/com/sun/tools/javac/code/ClassSymbolBuilder.java:1: error: reached end of file while parsing
    test
    ^
    Generated Source Files
    ======================

    /SOURCE_OUTPUT/com/sun/tools/javac/code/ClassSymbolBuilder.java:
    test
        at app//com.xenoterracide.bygger.ClassAnnotationTest.testImmutable(ClassAnnotationTest.java:51)
Tests run: 1, Failures: 1, Skipped: 0
```

Do you know if Compile-Testing is unusual in this regard? I wonder if Gradle prints more of the message if it matches a pattern that is hard-coded into the Gradle source?

**Comment by cpovirk** [comment]
Without that change (but at https://github.com/xenoterracide/bygger/commit/215f220f2ea817dc43716695c1e457180efdbee7, before your added logging), I do see the error during a plain `./gradlew test` but in the `STANDARD_OUT` section. I wonder if that could be part of any problem related to Gradle pattern matching:

```
ClassAnnotationTest > testImmutable() STANDARD_OUT
    /SOURCE_OUTPUT/com/sun/tools/javac/code/ClassSymbolBuilder.java:1: error: reached end of file while parsing
    test
    ^

ClassAnnotationTest > testImmutable() FAILED
    com.google.common.truth.AssertionErrorWithFacts at ClassAnnotationTest.java:51
```

**Comment by cpovirk** [comment]
Wait, no, sorry, some of your added logging was present even at that commit.

**Comment by cpovirk** [comment]
With a JUnit 5 assertion (`assertEquals(false, true)`), I see a similarly short error message:

```
ClassAnnotationTest > testImmutable() FAILED
    org.opentest4j.AssertionFailedError at ClassAnnotationTest.java:51
```

That's also what I see with a failure in another repo that uses JUnit 5 and Gradle.

I wonder if JUnit 4 is any different.

**Comment by xenoterracide** [comment]
yeah, no I see this affects assertj too... wat. I have a vague memory of applying `TestException.FULL` in the past in some project. I wonder if one of my other settings is messing with that...

**Comment by xenoterracide** [comment]
doesn't appear too, afaik all of my test configurations are in `our.java-test.gradle.kts`. My apologies on this, it never occurred to me that it might be a Gradle setting.

**Comment by cpovirk** [comment]
Ouch, I had assumed that Maven was the only build tool that was this way! And Gradle is no better with JUnit 4 tests, it appears :(
