### ISSUE TITLE
Use alternative compilers/wrappers in a given proposition chain

### ISSUE THREAD

**Issue by cgruber** [google/compile-testing#44]
I would love to be able to, say, supply alternative compilers/wrappers like error-prone, in order to be able to test compilation errors from things other than annotation processors.

**Comment by ronshapiro** [comment]
Implemented in [`com.google.testing.compile.Compiler(JavaCompiler)`](https://github.com/google/compile-testing/blob/6b329011414723b425ec96b2aa226b072a1efc4d/src/main/java/com/google/testing/compile/Compiler.java#L60)
