### ISSUE TITLE
Plain JUnit support/example needed (without org.truth0.Truth stuff) 

### ISSUE THREAD

**Issue by mmc41** [google/compile-testing#48]
Compile-testing is cool but even nicer if it can be used with plain JUnit tests also as I would like to limit dependencies and not using different test frameworks for different libraries. Especially since Truth is very alpha, and subject to change according to the docs.

**Comment by josketres** [comment]
+1

**Comment by cgruber** [comment]
You can use the CompilationRule bits without Truth, and exclude the dependency, if you wish to do that.  But Truth is at this point nearing a 1.0, and compile-testing was designed to be a fluent API rooted in the style of Truth, and abstracting away from the thing we use as the basis for the API is kind beyond the scope of what we're providing.
