### ISSUE TITLE
Use compile-testing & Truth plus runtime testing

### ISSUE THREAD

**Issue by JorgeCastilloPrz** [google/compile-testing#66]
I want to test my processor and test the classes autogenerated by it. I am getting a class not found error when i do my testing code like:

 ```java
@Before public void setup() {
    JavaFileObject source = JavaFileObjects.forSourceString("com.github.jorgecastilloprz.corleone.Test", Joiner.on('\n')
        .join("package com.github.jorgecastilloprz.corleone;",
            "public class Test {",
           "...stuff..."
            "}"));

    //Truth assertion
    Truth.ASSERT.about(javaSource())
        .that(source)
        .processedWith(myProcessor())
        .compilesWithoutError();
  }

  @Test public void jobDispatchTest() {
    JobDispatcher.getInstance().dispatchJobsWithContext("ObtainGames");
  } 
```

The dispatchJobsWithContext does a Class.forName() call inside it. I suppose the problem is that compile testing is prepared to test @ compile time, and that is the scope i am testing in. How can i reach the runtime to test  autogenerated classes then?

Thanks in advance.

**Comment by mhagnumdw** [comment]
What was your solution?
