### ISSUE TITLE
Ability to list output files of a compilation

### ISSUE THREAD

**Issue by liptga** [google/compile-testing#75]
If someone wants to create tests for existing annotation processor which generates files (xml description for example) from java files, then it is hard to figure out after a compilation what kind of files with what content were generated. I can check the content of some files ONLY if I know that they were generated. Today the list of generated files is encapsulated into InMemoryJavaFileManager.

It would be really good to have some alternative to that. I have thought about something like that:

``` java
assert_().
  about(javaSource()).
  that(JavaFileObjects.forResource( "Some.java") ).
  processedWith( new MyAnnotationProcessor() ).
  compilesWithoutError(an_instance_of_org_junit_rules_TemporaryFolder.getRoot());
```

The JavaFileManager could save the output files into the temp folder as well. Then the test case could easily check and see the list and contents of generated files.

I am surely not aware of the whole concept, so correct me please if my idea is somehow not realistic.

**Comment by cgdecker** [comment]
I believe this is possible now since you can use `Compiler` to compile and get a `Compilation` object that has various methods like `generatedFiles()` for getting data from the compilation.
