### ISSUE TITLE
A good example is missing

### ISSUE THREAD

**Issue by stephanenicolas** [google/compile-testing#95]
I had to run through a bunch of classes to find out where the assert_() call was coming from in the doc. 
The doc could be better for this and a nice little sample would be valuable.

**Comment by gk5885** [comment]
The first sentence in that the package doc _does_ point to `com.google.common.truth.Truth`…

**Comment by cgdecker** [comment]
Documentation currently seems to use `assertThat(compilation)` which would be a method in compile-testing rather than one in Truth, so I'm closing this as obsolete.
