### ISSUE TITLE
Generating other than .java files testing

### ISSUE THREAD

**Issue by vegegoku** [google/compile-testing#99]
I am trying to generate an HTML out fro annotated classes and i need to write unit testing for the generated .html files:

when i am generating .java files i testing them like this:
```java
Truth.assert_().about(javaSource()).that(JavaFileObjects.forResource("source class .java goes here"))
                .processedWith(new UiFormProcessor()).compilesWithoutError()
                .and()
                .generatesSources(JavaFileObjects.forSourceString("","expected generated class content goes here"));
```

and that works for me very well.

but when i am trying to generate an .html file and use the same code above, it result in an error like this 
`java.lang.AssertionError: Did not find a generated file corresponding to .java`

its seems that the generated files are expected to be java files all the time, i have been trying to figure out if i am calling the wrong methods or passing wrong arguments, but i could'nt make it work.

is there anyway to test none java generated sources like hml with this tool?

**Comment by tbroyer** [comment]
Are you looking for `generatesFileNamed(…).withStringContent(…)`?

**Comment by vegegoku** [comment]
That worked, thank you very much, i only needed to upgrade my maven dependency from 0.8 to 0.9 to find that method call.
i think more usage examples would really help here, and i wonder if i can somehow share my usage samples as part of my appreciation for this project.

**Comment by vegegoku** [comment]
now after upgrading to version 0.9 i am getting this error when trying to test .java generated source 
```java
Truth.assert_().about(javaSource()).that(JavaFileObjects.forResource(inputClassName))
                .processedWith(processor).compilesWithoutError().and()
                .generatesSources(JavaFileObjects.forSourceString("",result));
```

`java.lang.NoSuchMethodError: com.google.testing.compile.CompileTester$GeneratedPredicateClause.generatesSources(Ljavax/tools/JavaFileObject;[Ljavax/tools/JavaFileObject;)Ljava/lang/Object;`

**Comment by tbroyer** [comment]
`java.lang.NoClassDefFoundError: com/google/common/base/MoreObjects` means you're probably using an outdated version of Guava (17.0 or earlier) or missing Guava entirely. compile-testing 0.8 had a dependency on Guava 16.0.1, compile-testing 0.9 has a dependency on Guava 19.0.

**Comment by vegegoku** [comment]
Yup you are right.
running `mvn dependency:tree` and i found that i am using `com.google.auto.service:auto-service:1.0-rc1` which depends on guava 16, updating to auto-service:1.0-rc2 resolved the issue since it depends on guava 18.

thanks.
